"""Generate deterministic Stage-9 tables/figure scaffolds from frozen formulas."""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TABLES = ROOT/'tables'; FIGURES = ROOT/'figures'; RESULTS = ROOT/'results'
FREEZE_ID = 'IPCRVC-THEORY-FREEZE-2026-09-07-v1'
for p in (TABLES,FIGURES,RESULTS): p.mkdir(exist_ok=True)

threshold_table = r'''% Auto-generated by scripts/generate_outputs.py. Do not edit by hand.
\begin{table}[htbp]
\centering
\caption{Frozen threshold objects}
\label{tab:thresholds}
\begin{tabular}{lll}
\toprule
Object & Expression & Scope \\
\midrule
Coordinated fixed-capacity threshold & $A^P=\Delta$ & Baseline \\
Decentralized threshold & $A^N=\Delta/(1-\alpha)$ & Baseline \\
Threshold gap & $A^N-A^P=\alpha\Delta/(1-\alpha)$ & $\Delta>0,\ 0<\alpha<1$ \\
Constant-capture coordinated threshold & $G^P=\Delta$ & Binary switching lemma \\
Constant-capture local threshold & $G^N=\Delta/\lambda$ & $0<\lambda<1$ \\
\bottomrule
\end{tabular}
\end{table}
'''
(TABLES/'thresholds.tex').write_text(threshold_table,encoding='utf-8')
svg='''<svg xmlns="http://www.w3.org/2000/svg" width="900" height="220" viewBox="0 0 900 220">
<rect x="50" y="80" width="240" height="55" fill="#eeeeee" stroke="#333333"/><rect x="290" y="80" width="260" height="55" fill="#dddddd" stroke="#333333"/><rect x="550" y="80" width="300" height="55" fill="#cccccc" stroke="#333333"/>
<text x="170" y="112" text-anchor="middle" font-size="18">Both duplicate</text><text x="420" y="103" text-anchor="middle" font-size="16">Planner reallocates;</text><text x="420" y="123" text-anchor="middle" font-size="16">locals duplicate</text><text x="700" y="103" text-anchor="middle" font-size="16">Differentiated NE emerge;</text><text x="700" y="123" text-anchor="middle" font-size="16">symmetric NE also exists</text>
<line x1="50" y1="155" x2="850" y2="155" stroke="#111111" stroke-width="2"/><line x1="290" y1="145" x2="290" y2="165" stroke="#111111"/><line x1="550" y1="145" x2="550" y2="165" stroke="#111111"/>
<text x="290" y="190" text-anchor="middle" font-size="16">A^P = 1</text><text x="550" y="190" text-anchor="middle" font-size="16">A^N = 2</text><text x="450" y="215" text-anchor="middle" font-size="14">Illustration only: alpha=1/2, Delta=1</text></svg>\n'''
(FIGURES/'phase_regions.svg').write_text(svg,encoding='utf-8')
manifest={'freeze_id':FREEZE_ID,'generator':'scripts/generate_outputs.py','generated':['tables/thresholds.tex','figures/phase_regions.svg'],'note':'Generated objects are exposition artifacts; theorem validity is established by symbolic proofs/tests, not by this figure.'}
(RESULTS/'generated_manifest.json').write_text(json.dumps(manifest,indent=2)+'\n',encoding='utf-8')
print('Generated deterministic outputs')
